-- CreateTable
CREATE TABLE "sdgdata" (
    "Country" VARCHAR(512) NOT NULL,
    "2023 SDG Index Score" VARCHAR(512),
    "2023 SDG Index Rank" VARCHAR(512),
    "Regions used for the SDR" VARCHAR(512),
    "SDG1: No Poverty" VARCHAR(512),
    "SDG1 TimeSeries" VARCHAR(512),
    "SDG2: No Hunger" VARCHAR(512),
    "SDG2 TimeSeries" VARCHAR(512),
    "SDG3: Good Health and Well-Being" VARCHAR(512),
    "SDG3 TimeSeries" VARCHAR(512),
    "SDG4: Quality Education" VARCHAR(512),
    "SDG4 TimeSeries" VARCHAR(512),
    "SDG5: Gender Equality" VARCHAR(512),
    "SDG5 TimeSeries" VARCHAR(512),
    "SDG6: Clean Water and Sanitation" VARCHAR(512),
    "SDG6 TimeSeries" VARCHAR(512),
    "SDG7: Affordable and Clean Energy" VARCHAR(512),
    "SDG7 TimeSeries" VARCHAR(512),
    "SDG8: Decent Work and Economic Growth" VARCHAR(512),
    "SDG8 TimeSeries" VARCHAR(512),
    "SDG9: Industry, Innovation and Infrastructure" VARCHAR(512),
    "SDG9 TimeSeries" VARCHAR(512),
    "SDG10: Reduced Inequalities" VARCHAR(512),
    "SDG10 TimeSeries" VARCHAR(512),
    "SDG11: Sustainable Cities and Communities" VARCHAR(512),
    "SDG11 TimeSeries" VARCHAR(512),
    "SDG12: Responsible Consumption and Production" VARCHAR(512),
    "SDG12 TimeSeries" VARCHAR(512),
    "SDG13: Climate Action" VARCHAR(512),
    "SDG13 TimeSeries" VARCHAR(512),
    "SDG14: Life Below Water" VARCHAR(512),
    "SDG14 TimeSeries" VARCHAR(512),
    "SDG15: Life on Land" VARCHAR(512),
    "SDG15 TimeSeries" VARCHAR(512),
    "SDG16: Peace, Justice and Strong Institutions" VARCHAR(512),
    "SDG16 TimeSeries" VARCHAR(512),
    "SDG17: Partnerships for the Goals" VARCHAR(512),
    "SDG17 TimeSeries" VARCHAR(512),

    CONSTRAINT "sdgdata_pkey" PRIMARY KEY ("Country")
);

